# Site
repository: ImJaewooChoi/ImJaewooChoi.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jaewoo Choi
title: AI & Computer Vision Engineer
email: iam.jaewoochoi@gmail.com
# email_title: Email (Email title override)
website: https://imjaewoochoi.github.io
# website_title: Web (Website title override)
address: Seoul, South Korea

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: iam_jaewoochoi
github_username: ImJaewooChoi
# stackoverflow_username: "00000001"
# dribbble_username: 
# facebook_username: 
# flickr_username: 
# instagram_username: 
linkedin_username: jaewoo-choi-955340356
# xing_username: 
# pinterest_username: 
# youtube_username: 
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
- title: Portfolio
  icon: fas fa-globe
  url: https://imjaewoochoi.github.io
- title: Kaggle
  icon: fab fa-kaggle
  url: https://www.kaggle.com/loveacaji
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: ""
about_content: ""
about_profile_image: images/profile.jpg

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Daedong AILab
        sub_title: AI Researcher
        caption: May 2024 - Present
        description: | # this will include new lines to allow paragraphs
          Advanced AI research and development in agricultural and industrial automation. Implementation of cutting-edge machine learning algorithms for real-world applications. Collaboration on innovative AI solutions for industry-specific challenges.

      - layout: left
        title: PLAIF
        sub_title: Computer Vision Engineer
        caption: Jan 2023 - Apr 2024 · 1 yr 4 mos
        description: | # this will include new lines to allow paragraphs
          Developed object detection and segmentation models using various vision sensors. Implemented 6D pose estimation algorithms for industrial applications. Designed and optimized computer vision pipelines for real-time processing. Integrated multi-sensor fusion systems for enhanced perception accuracy.

      - layout: left
        title: FS Solution Co., Ltd.
        sub_title: Computer Vision Engineer
        caption: May 2022 - Dec 2022 · 8 mos
        description: | # this will include new lines to allow paragraphs
          Developed autolabeling tools for autonomous driving applications. Created automated data annotation systems for training datasets.

  - title: Projects
    layout: list
    content:
      - layout: left
        title: "Orchard Robotics: Multi-Modal Dataset & Detection Model"
        caption: Apr 2025 - Present
        description: | # this will include new lines to allow paragraphs
          Led 5TB multi-modal agricultural data collection project for orchard robotics. Established standardized annotation protocols and automated validation pipelines. Processed captioning data for multi-modal object detection model development.

      - layout: left
        title: Object Tracking
        caption: Mar 2025 - May 2025
        description: | # this will include new lines to allow paragraphs
          Developed RGB-D camera-based object detection and tracking algorithms for mobile platforms. Implemented BEV tracking with TensorRT optimization for real-time embedded systems operation.

      - layout: left
        title: Harvesting Robot
        caption: May 2024 - Dec 2024
        description: | # this will include new lines to allow paragraphs
          Developed AI-based agricultural harvesting robot with computer vision recognition and diffusion-based path generation. Trained on 5,000 video dataset and showcased at CES 2025.

      - layout: left
        title: Auto Assemble
        caption: Jul 2023 - Mar 2024
        description: | # this will include new lines to allow paragraphs
          Developed 3D vision-based assembly system without CAD models using ToF and RGB-D cameras. Achieved 92% assembly success rate through precise pose estimation and depth refinement.

      - layout: left
        title: Bin Picking
        caption: Feb 2023 - Jul 2023
        description: | # this will include new lines to allow paragraphs
          Implemented automated bin picking system with instance segmentation and CAD-based pose estimation. Achieved 95% picking success rate and 93% task completion rate.

      - layout: left
        title: Auto Labeling
        caption: Jun 2022 - Dec 2022
        description: | # this will include new lines to allow paragraphs
          Developed auto-labeling tool for autonomous driving data annotation. Automated bounding box generation for vehicles, pedestrians, and traffic lights, significantly reducing manual annotation time.

  - title: Awards & Honors
    layout: list
    content:
      - layout: left
        title: Korean Patent Achievement
        caption: Patent Issued August 8, 2024
        description: | # this will include new lines to allow paragraphs
          AI-based robot pose estimation system patent (KOR 1020230187604) for converting 2D images to 3D data for precise robotic control.

      - layout: left
        title: UBC Ovarian Cancer Subtype Classification and Outlier Detection (UBC-OCEAN)
        caption: Bronze Medal · Oct 2023 - Jan 2024
        description: |
          Vision Transformer ensemble model for cancer diagnosis classification using WSI high-frequency region tiling and 5-Fold CV with TTA optimization.

      - layout: left
        title: Kaggle Image Matching Challenge 2022
        caption: Silver Medal · Apr 2022 - Jun 2022
        description: |
          Dynamic pipeline combining DISK and SIFT feature extraction with MAGSAC geometric filtering for robust image matching under challenging conditions.

      - layout: left
        title: Kaggle Happy Whale Competition
        caption: Bronze Medal · Feb 2022 - Apr 2022
        description: | # this will include new lines to allow paragraphs
          Two-stage pipeline combining classification and similarity search using ArcFace loss function for high-quality embeddings and k-NN refinement.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Seokyeong University
        sub_title: Bachelor of Engineering (B.E.)
        caption: March 2016 - August 2022
        description: | # this will include new lines to allow paragraphs
          Department of Industrial Management Systems Engineering with Multidisciplinary Major in Big Data Business Intelligence.
          
          GPA: 3.34/4.5
          
      - layout: left
        title: Apgujeong High School
        caption: 2011 - 2014
        description: | # this will include new lines to allow paragraphs
          General high school education

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
