# Site
repository: ImJaewooChoi/ImJaewooChoi.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jaewoo Choi
title: AI & Computer Vision Engineer
email: iam.jaewoochoi@gmail.com
# email_title: Email (Email title override)
phone: +82-10-0000-0000
# phone_title: Phone (Phone title override)
website: https://imjaewoochoi.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username: ImJaewooChoi
# stackoverflow_username: "00000001"
# dribbble_username: 
# facebook_username: 
# flickr_username: 
# instagram_username: 
linkedin_username: jaewoo-choi
# xing_username: 
# pinterest_username: 
# youtube_username: 
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
- title: Portfolio
  icon: fas fa-globe
  url: https://imjaewoochoi.github.io
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
# about_profile_image: images/profile.jpg
# about_content: | # this will include new lines to allow paragraphs
#   Hello! I'm **Jaewoo Choi**, an **Artificial Intelligence Developer** passionate about cutting-edge technologies and innovative solutions.
# 
#   My main areas of interest include:
#     - **Multimodal AI**: Developing systems that can understand and process multiple types of data (text, images)
#     - **Robotics**: Creating intelligent robotic systems and autonomous agents
#     - **Computer Vision**: Advanced image processing and visual understanding
#     - **Machine Learning**: Deep learning architectures and neural networks
#     - **Natural Language Processing**: Language understanding and generation models

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Multimodal AI Research
        link: https://github.com/ImJaewooChoi
        link_text: View Research
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/ImJaewooChoi
        quote: >
          Cross-modal learning and understanding systems
        description: | # this will include new lines to allow paragraphs
          Research and development of multimodal AI systems that can understand and process 
          multiple types of data including text, images, audio, and video. Focus on creating 
          unified representations for cross-modal tasks.
          
      - layout: left
        title: Robotics & Computer Vision
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/ImJaewooChoi
        quote: >
          Intelligent autonomous systems with advanced perception
        description: |
          Development of robotic systems with enhanced computer vision capabilities.
          Projects include object detection, manipulation planning, and human-robot interaction
          using ROS and modern deep learning frameworks.
          
      - layout: left
        title: Personal Portfolio Website
        link: https://imjaewoochoi.github.io
        link_text: Visit Portfolio
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/ImJaewooChoi/ImJaewooChoi.github.io
        quote: >
          Modern Jekyll-based portfolio website
        description: |
          Responsive personal portfolio website built with Jekyll and GitHub Pages.
          Features modern design, dark mode support, and showcases AI research projects.

  - title: Experience
    layout: list
    content:
      - layout: right
        title: AI Research & Development
        sub_title: Artificial Intelligence Developer
        caption: Present
        quote: >
          Advancing multimodal AI and robotics research
        description: | # this will include new lines to allow paragraphs
          • Research and development of multimodal AI systems combining computer vision, NLP, and robotics
          • Implementation of state-of-the-art deep learning models for cross-modal understanding
          • Development of robotic perception systems using ROS and modern AI frameworks
          • Collaboration on cutting-edge projects in embodied AI and human-robot interaction

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Seokyeong University
        sub_title: Bachelor of Engineering (B.E.)
        caption: March 2016 - August 2022
        quote: >
          Industrial Management Systems Engineering & Big Data Business Intelligence
        description: | # this will include new lines to allow paragraphs
          • **Major**: Department of Industrial Management Systems Engineering
          • **Multidisciplinary Major**: Big Data Business Intelligence
          • **GPA**: 3.34/4.5
          • Comprehensive study of industrial systems, operations research, and data analytics
          • Specialized in big data processing, business intelligence, and AI applications in industrial systems
          • Strong foundation in systems engineering, optimization, and data-driven decision making

  - title: Skills & Interests
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Technical Skills:**
      - **Programming Languages:** Python, C++, JavaScript, Java, MATLAB
      - **AI/ML Frameworks:** TensorFlow, PyTorch, Keras, Scikit-learn, OpenCV
      - **Multimodal AI:** CLIP, DALL-E, GPT-4 Vision, Stable Diffusion
      - **Robotics:** ROS (Robot Operating System), Gazebo, MoveIt
      - **Computer Vision:** OpenCV, MediaPipe, YOLO, Detectron2
      - **Cloud & MLOps:** AWS, Docker, Kubernetes, MLflow, Weights & Biases
      - **Development Tools:** Git, Linux, Jupyter, VS Code

      **Research Interests:**
      - **Multimodal Learning:** Cross-modal understanding and generation
      - **Robotics & Embodied AI:** Intelligent autonomous systems
      - **Computer Vision:** Object detection, segmentation, and tracking
      - **Human-Robot Interaction:** Natural and intuitive robot interfaces
      - **Edge AI:** Optimizing AI models for real-time applications

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
